# Generated by Django 4.2.10 on 2024-04-21 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refferral_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='reffered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='was_reffered', to=settings.AUTH_USER_MODEL),
        ),
    ]
